version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_DATABASE: roasanta
    volumes:
      - mongo-data:/data/db
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://mongo:27017/roasanta
    depends_on:
      - mongo
    networks:
      - roasanta-net
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - roasanta-net
networks:
  roasanta-net:
    driver: bridge
volumes:
  mongo-data:
